addons:
  apt:
    packages:
    - oracle-java8-installer
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: ce515bfd-2bc8-4137-b186-8c1535a0c0cb
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 360 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install: []
before_script:
- travis/before_script.sh
branches: ''
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=ce515bfd-2bc8-4137-b186-8c1535a0c0cb
script: '[''mvn test -Ptest-output'', ''find $HOME/.m2 -name "_remote.repositories"
  | xargs rm'', ''find $HOME/.m2 -name "resolver-status.properties" | xargs rm -f'']'
sudo: false
# Modified by Insights Service at 2016-10-26 11:46:58.002661
